### ISSUE TITLE
malformed 'depends' fields do not cause an error

### ISSUE THREAD

**Issue by grigorescu** [bro/package-manager#13]
Justin's scan detection is an example here. Can't install it, because it needs the darknet script, but the tests won't pass until the darknet script is installed.

**Comment by jsiwek** [comment]
It should already be the case that dependencies get installed before running tests -- actually the dependencies and the tested package get installed into an isolated staging area before performing the real installation on them.

What happened here was that the 'depends' field of the package was malformed, causing it to not actually recognize that the darknet package was a dependency it needed and so it silently proceeded without an error message.  It now should raise an error message and abort.

And then there was also a second problem in that the scan detection package was explicity setting BROPATH, causing it to try and look in the actual installation path instead of the staging area that bro-pkg uses for testing.

Also, your original wording made it seem like you couldn't actually install it if the tests didn't pass?  I think it should have been prompting to "proceed with installation anyway", let me know if not.

Anyway, should work once https://github.com/ncsa/bro-simple-scan/pull/2 is merged.

**Comment by grigorescu** [comment]
Thanks, Jon. Sorry for the unclear wording, you are correct. I was relaying the issue and didn't quite phrase it very well.
