### ISSUE TITLE
broctl install doesn't preserve symlinks bro-pkg's package installation tree

### ISSUE THREAD

**Issue by dopheide-esnet** [bro/package-manager#14]
Debate:  Issue with bro-pkg or issue with how developers (ie Justin) should load dependent packages?

bro/ncsa/bro-is-darknet is required by bro/ncsa/bro-simple-scan.

The simple scan package loads 'bro-is-darknet', but bro-pkg also adds bro-is-darknet to packages.bro so it's loaded twice causing errors with duplicate defines.

Can be easily resolved by 'bro-pkg unload bro/ncsa/bro-is-darknet' for now.

**Comment by dopheide-esnet** [comment]
Additional info... ordering of loads in packages.bro does not appear to be tied to dependencies.

**Comment by dopheide-esnet** [comment]
Update:  Justin is fixing the first issue by specifying 'packages/..." in his @load directive.  This makes the second issue irrelevant.

Documentation should indicate that need.
Also, should the package symlinks exist?

**Comment by jsiwek** [comment]
- Package authors should always `@load` dependencies from within their own scripts.
-  It's desirable for packages to `@load` others without having to use the 'packages/...' prefix as it should allow the package easier to install for those that don't wish to use bro-pkg.  Using the prefix for the moment can definitely be a workaround, but ultimately I think Bro should be made to properly prevent duplicate `@loads` (I recall it should be doing this already for scripts in general, but likely that logic is not handling symlinks properly), I'll have to check into it.
- Given all the above, the particular order of `@load`s in the autogenerated packages.bro shouldn't matter for users.

> Also, should the package symlinks exist?

If you mean the symlinks in 'site', yes, those should always exist.

**Comment by JustinAzoff** [comment]
> I recall it should be doing this already for scripts in general, but likely that logic is not handling symlinks properly), I'll have to check into it.

Yeah, the problem was specifically that it was loading

site/packages/bro-is-darknet/...
site/bro-is-darknet/...

and not realizing that they were the same file.. I think a call to `realpath` may be the solution?

**Comment by jsiwek** [comment]
Looks like bro handles loading symlinks fine -- to detect duplicate loads it compares inode numbers and it gets those numbers via fstat'ing an already opened file.  i.e. the symlink has already been followed, so loading a script directly or via a symlink both resolve to the same inode number.

The only other thing I came across was that local.bro has `@load misc/scan` by default.  So if you have that being loaded and then also try to load the bro/ncsa/bro-simple-scan package, you will get errors indicating duplicate definitions of the `Address_Scan` and `Port_Scan` notice enums.  And that's an actual problem with the package since they are defined in both scripts under the same namespace.  I'd probably change the module name used by the bro-simple-scan package from "Scan" to "SimpleScan" to fix that.

Could that have been the original problem?  If not, I'll probably need some explicit directions to reproduce the error messages you were seeing.

**Comment by dopheide-esnet** [comment]
We thought misc/scan was the problem originally as well.   Here's how to
reproduce:

Verify:

[root@montu-dev site]# grep scan local.bro
# Load the scan detection script.
#@load misc/scan

Remove "packages" from the bro-is-darknet @load in bro-simple-scan:

[root@montu-dev site]# grep "@load" packages/bro-simple-scan/scan.bro
@load base/frameworks/notice
@load base/utils/time
#@load packages/bro-is-darknet
@load bro-is-darknet

[root@montu-dev site]# broctl deploy
...
starting logger ...
logger terminated immediately after starting; check output with "diag"

[root@montu-dev site]# broctl diag
...
warning in
/usr/local/bro/spool/installed-scripts-do-not-touch/site/packages/./bro-is-darknet/./main.bro,
line 16 and
/usr/local/bro/spool/installed-scripts-do-not-touch/site/bro-is-darknet/./main.bro,
line 16: redefinition requires "redef" (Site::darknet_address_space)
error in
/usr/local/bro/spool/installed-scripts-do-not-touch/site/packages/./bro-is-darknet/./main.bro,
line 16: already defined (Site::darknet_address_space)
internal warning in
/usr/local/bro/spool/installed-scripts-do-not-touch/site/bro-is-darknet/./main.bro,
line 16: Duplicate identifier documentation: Site::darknet_address_space
...

-Dop

**Comment by JustinAzoff** [comment]
scan.bro has since been changed to do

    @load packages/bro-is-darknet

so I don't know if you can reproduce it that way anymore

**Comment by dopheide-esnet** [comment]
You can, you just have to edit the package by hand to replicate.  Sorry,
that wasn't clear.

**Comment by jsiwek** [comment]
Thanks, I can reproduce now.  I had been trying to use a forked version of the package with the 'packages' prefix removed, but only tested with bro itself and not broctl.  Problem seems to be when you install/deploy via broctl, it does not preserve the existing symlink structure and instead makes full copies of all files/dirs so it becomes possible to accidentally load the same script twice since one is no longer loaded via a symlink.  I'll look into fixing that in broctl.

**Comment by jsiwek** [comment]
Yeah, the fix will need to be in broctl.  Merge request for that here: https://bro-tracker.atlassian.net/browse/BIT-1846
