### ISSUE TITLE
Ordering of aggregate metadata

### ISSUE THREAD

**Issue by 0xxon** [bro/package-manager#21]
The order of the aggregate metadata currently does not seem to be the same when several people on different systems update it. I know that there already was a past patch to fix this behavior, however it still does not seem to fix all cases.

For illustration - my current ordering is: https://github.com/bro/packages/commit/355d1e11790f910b32b796fd296ba2f7be3c2923. The updates in that commit are from a previous commit of Seth with different ordering; commit in https://github.com/bro/packages/commit/610ce6b95957f9a1c7534d29b361edc266817820

Both of us are running bro-pkg 1.2.1. The difference seems to be that I am running it under python 2.7.14 and Seth is running on 3.5.3.

**Comment by jsiwek** [comment]
I think it may be fixed once you both upgrade to bro-pkg 1.2.2.

The previous patch from #6 I think made the order stable across python versions, but not across operating systems and I didn't catch the later since I only tested on a single host.  Guessing it may have been python's os.walk() traversing a directory tree differently depending on OS.

I'm on macOS 10.13 and the order I was getting was the same as Seth's.  After applying the patch, the order I get is the same as yours.

**Comment by 0xxon** [comment]
Thanks a lot :)

**Comment by jsiwek** [comment]
Seems like the patch worked for you, let me know if not.
