### ISSUE TITLE
Support prebuilt/binary bundles

### ISSUE THREAD

**Issue by SleuthKid** [bro/package-manager#25]
To be useful in any way as a "package manager" the unbundle command should not be depended on a bro-dist directory setting. I want to be able to prebuild plugins and ship them to fortified sensor boxes with a limited amount of packages.

```
# bro-pkg unbundle /home/user/bro_stretch_plugins.bundle
The following packages will be INSTALLED:
  https://github.com/ntop/bro-pf_ring (master)

Proceed? [Y/n] Y
error: failed to unbundle /home/user/bro_stretch_plugins.bundle: package build_command failed, see log in /root/.bro-pkg/logs/bro-pf_ring-build.log

# cat /root/.bro-pkg/logs/bro-pf_ring-build.log
=== STDERR ===
=== STDOUT ===
Cannot determine Bro source directory, use --bro-dist=DIR.
```

**Comment by jsiwek** [comment]
They currently just support source-only packages because the main goals for bundles were (1) ability to easily recreate identical package config/states across multiple servers and (2) offline bro-pkg operation, since servers in Bro deployments often have limited external internet connectivity.

I think the separate goal of supporting prebuilt/binary packages in bundles has not been a priority because most people running BroControl are fine having build tools on one, centralized manager node, which builds and ships everything out to the even-more-fortified worker nodes.  The only benefit of prebuilt package bundles is it allows you to change which system has the build tools on it.  Where are you expecting the system w/ build tools to be for your use-case?

**Comment by SleuthKid** [comment]
As I maintain the debian package for bro-pkg my ultimate goal would be to provide a fully functional bro environment for debian/ubuntu (bro + broctl + bro-pkg) to be installed by apt from the standard repos, without needing any source code checkout.

This would likely increase the usability of bro to entry level people and give them a quick start.

As already discussed in IRC and in another issue an aditional bro-dev package might be the right solution.

**Comment by jsiwek** [comment]
Thanks, that goal does make a lot of sense and I also wonder about what the ideal resolution would be.  A bro-dev package does seem generally warranted.  Other thoughts:

- Bro plugin developers that don't necessarily even use or care about bro-pkg might also benefit from a bro-dev package.
- For bro-pkg users, either the `bundle` or `unbundle` command is always going to need bro-dev resources (e.g. headers) unless the given bro package they are operating on includes prebuilt binaries in itself (which is not likely and/or not reasonable to expect packagers to do for every possible platform a user may want)
- There was already work/intention towards having a central web interface for browsing bro packages along with infrastructure for automated testing / security audits of packages.  It makes sense for that same infrastructure to also automate builds of bro packages for all major platforms so that bro-pkg can use those directly instead of having users compile locally.  No idea what the ETA on getting that all working would be, would need research/design.

For now, having a bro-dev package on debian seems right for what you're trying to do.  Let me know if you're thinking something else.

**Comment by SleuthKid** [comment]
Thank you for the extensive insight 👍 
I am not that into the core source code of bro. I would probably partner with the bro package maintainer @hillu to generate an overview of which header files would be needed for a bro-dev subset.

This will probably come with some minor changes to the bro core source code to release some dependencies.

On a side note: It would be great for packaging if you could stick to semantic versioning when tagging releases on github (1.3.0 instead of 1.3) ❤️ 😃

**Comment by jsiwek** [comment]
> I am not that into the core source code of bro. I would probably partner with the bro package maintainer @hillu to generate an overview of which header files would be needed for a bro-dev subset.
> 
> This will probably come with some minor changes to the bro core source code to release some dependencies.

Yeah, this may be a non-trivial project -- historically, bro has never been developed w/ the intention of being used as a public API, just a command-line tool.  Revisiting that in order to be able to ship/install just development headers is something that's only been put on bro's roadmap recently, but without any spare cycles in the core dev team to devote to it yet.  Any extra help, maybe even in just starting to organize a high-level approach to tackling the problem would be awesome.

> On a side note: It would be great for packaging if you could stick to semantic versioning when tagging releases on github (1.3.0 instead of 1.3) ❤️ 😃

Sure, I don't think that will be a problem.

**Comment by jsiwek** [comment]
I'll just close this for now -- I don't think there's any near-term changes that can be done in bro-pkg to solve your problem and I also think prebuilt bro package distribution is a larger project to undertake than just handling it in bundle/unbundle command.
