### ISSUE TITLE
bro-pkg doesn't support external library dependencies

### ISSUE THREAD

**Issue by JonZeolla** [bro/package-manager#9]
This is a feature request.

As of right now, it doesn't seem like bro-pkg's [`depends`](http://bro-package-manager.readthedocs.io/en/stable/package.html#depends) has support for external libraries.  For instance, for the kafka writer plugin package that [I'm working on](https://github.com/JonZeolla/metron-bro-plugin-kafka/tree/bro-pkg), I need to build the plugin against librdkafka version 0.9.4 or greater.  Right now I'm handling this via a hack in bro-pkg.meta's `build_command` (below), but it could be better, especially because librdkafka is often packaged and available for download (librdkafka1 and librdkafka-dev in Ubuntu/Debian, RPMs librdkafka and librdkafka-devel, Gentoo's dev-libs/librdkafka, etc.).  
```
build_command = ( if [ ! -a /usr/local/lib/librdkafka.so ]; then curl -L https://github.com/edenhill/librdkafka/archive/v0.9.4.tar.gz | tar xvz && cd librdkafka-0.9.4/ && ./configure --prefix=/usr/local --enable-sasl && make && sudo make install && cd - ; else if [ $(python -c "from ctypes import *; minver = 0x904ff; dll = cdll.LoadLibrary(\"/usr/local/lib/librdkafka.so\"); version = dll.rd_kafka_version(); exit(0) if minver >= version else exit(1)") ]; then echo "At least version 0.9.4 of librdkafka is installed"; else echo "Please manually upgrade librdkafka to at least version 0.9.4"; exit 1; fi; fi && ./configure --bro-dist=%(bro_dist)s --with-librdkafka=/usr/local && make )
```

**Comment by jsiwek** [comment]
Likely going to need to go through a round or two of design/feedback to figure out how to handle this.  Two different approaches come to mind:

1. bro-pkg provides a more standardized way to build/install external dependencies from their source code

Pros:
- Package author shouldn't need any platform-specific knowledge as the commands you use to build/install are likely the same across platforms.
- Easy to integrate into the bro-pkg bundle/unbundle process.  E.g. package author could specify a URL to a tarball (which may even point to a file that's been committed within the package's git repo itself) and that tarball is easily included in bundles and built when unbundling it on other nodes.

Cons:
- Providing a reliable way to uninstall or otherwise clean up orphaned, external dependencies is trickier.  E.g. we can't rely on every single project out there to give us a `make uninstall` target we can use, so likely would have to ask bro package authors to accept burden of providing some sort of install_manifest.txt that we can use to clean up extra files.
- If external dependencies have their own complex dependency graph, then that's a fair bit of work for package authors to implement -- they have to first stick all relevant tarball URLs in bro-pkg.meta, then write some build scripts for each one, and finally also create an install_manifest.txt

2. bro-pkg provides a standardized bridge to the package managers of various platforms (e.g. yum, apt, brew, etc).

Pros:
- Fairly easy to install/uninstall the external dependencies.
- Complex external dependency graphs are already completely handled by the platform's various package managers.

Cons:
- May not integrate well with the bro-pkg bundle/unbundle workflow unless we include all the installed artifacts from the external dependency.  I think this may not be that bad as most platforms can provide this information back to bro-pkg (e.g. `dpkg --listfiles <package>`)
- It's up to the package author to do a little research/work to find the correct name for the external dependency package on each platform they want to support

Thoughts?

I lean toward the second approach at the moment.

**Comment by JonZeolla** [comment]
I lean towards the second approach because that would also provide reasonable version checking.  As you can see in my one liner it was somewhat awkward to do so when installed from source.

**Comment by jsiwek** [comment]
> As you can see in my one liner it was somewhat awkward to do so when installed from source.

Yeah, though to expand on the fully standardized compile-from-source approach I was trying to imagine -- I was thinking it could be possible to add extra mechanisms that keep the bro-pkg.meta simpler to maintain.  e.g. maybe simply specifying the names of separate build scripts that you maintain as other files inside your git repo, thus making it less awkward than the huge-one-liner you have to do now.

**Comment by JonZeolla** [comment]
Gotcha, yeah that would be better but I still would call it awkward.  In this case, the method of version checking wouldn't change (it would just be broken out).  Also, dealing with a system that has a newer version than the minimum required is nicer using a platform's package manager.

**Comment by rsmmr** [comment]
I have to say that the idea of bro-pkg going ahead and installing system components leaves me uneasy (in both models, 1 & 2). If we did that there could be some pretty substantial side effects to installing a bro-pkg that people may never realize nor want; and uninstalling the Bro package would often not make them go away (even in model 2, I don't think we could go ahead and do "yum uninstall", something else may be using that system package too). It would also mean that installing the package will require root.

Is this something other package managers would do?

One idea: could we do this through local installations that stay within the install path for the Bro package? The package would built, e.g., libkafka with that --prefix, get it installed there, and then set up runtime paths so that that version is preferred over any system-wide installation. That would also solve any versioning problems.

One more idea: a "softer" version of this would be not installing the dependency but just have a test that it's there. If it isn't, bro-pkg would abort and could also print out instructions on what to do.

**Comment by jsiwek** [comment]
> uninstalling the Bro package would often not make them go away (even in model 2, I don't think we could go ahead and do "yum uninstall", something else may be using that system package too).

Right that part would be awkward to automatically handle, best case would probably be that we can emit a warning to user about possibly orphaned external dependencies.

> It would also mean that installing the package will require root.

Yeah, and external dependencies interacting with bundles is awkward.  I'd rather not just take provided system files, stick them in the bundle, and then force them into the right place on the 'unbundle' side.

> Is this something other package managers would do?

Not sure, I've only briefly looked again at rust's cargo and npm to see if I could find what they do.  For the later, one example would be https://github.com/Shouqun/node-dbus, and it looks like they just have directions in the README for installing OS dependencies, e.g. "run sudo apt-get ..."

> One idea: could we do this through local installations that stay within the install path for the Bro package? The package would built, e.g., libkafka with that --prefix, get it installed there, and then set up runtime paths so that that version is preferred over any system-wide installation. That would also solve any versioning problems.

Yeah, maybe possible.  Not sure how much hassle it is for package authors to still maintain the awkward build_command for that?  Maybe not that bad if the build_command just points to a shell script that could be maintained separately instead of a big one-liner.

And what about bundling?  Would we need extra mechanisms to make sure external dependency source code gets included in the bundle to be built upon unbundling? 

> One more idea: a "softer" version of this would be not installing the dependency but just have a test that it's there. If it isn't, bro-pkg would abort and could also print out instructions on what to do.

Yeah, I was also going to suggest something like may be sufficient.  Maybe even something like a 'extra_instructions' field that you put in bro-pkg.meta.  Then at install time, bro-pkg can automatically display those instructions in the confirmation prompt.  It could basically tell the user "before proceeding make sure you install external platform dependencies X, Y, and Z on any systems where this package will be used".  Or just any arbitrary text to help users walkthrough complicated prerequisites.  I think that's a good thing because we probably can't actually anticipate all the kinds of crazy setups any given package may require in the future, but with such a field we can just leave it up to the packager to maintain.

**Comment by JonZeolla** [comment]
> I have to say that the idea of bro-pkg going ahead and installing system components leaves me uneasy (in both models, 1 & 2). If we did that there could be some pretty substantial side effects to installing a bro-pkg that people may never realize nor want; and uninstalling the Bro package would often not make them go away (even in model 2, I don't think we could go ahead and do "yum uninstall", something else may be using that system package too). It would also mean that installing the package will require root.
>
> Is this something other package managers would do?
>
> One idea: could we do this through local installations that stay within the install path for the Bro package? The package would built, e.g., libkafka with that --prefix, get it installed there, and then set up runtime paths so that that version is preferred over any system-wide installation. That would also solve any versioning problems.

Yeah, I actually suggested this to Jon in person at BroCon so we don't have to worry about a situation where someone (1) uses bro-pkg which pulls in a dependency, (2) installs a second tool which depends on the initial dependency, (3) a `bro-pkg remove` removes the dependency because it was installed by bro-pkg, causing an issue in the second tool.  This is also why I broke out #11 into its own issue; I would want to not install deps unless it was explicitly approved by the user.

**Comment by JonZeolla** [comment]
> Yeah, maybe possible. Not sure how much hassle it is for package authors to still maintain the awkward build_command for that? Maybe not that bad if the build_command just points to a shell script that could be maintained separately instead of a big one-liner.

Couldn't it just be abstracted?  Why would the package manager need to specify where the dependency goes, as long as it gets handled (adding `--prefix` behind the scenes but allowing (a generally bad practice of) overrides).

I'm also game for a softer touch here.

**Comment by jsiwek** [comment]
> Couldn't it just be abstracted? Why would the package manager need to specify where the dependency goes, as long as it gets handled (adding --prefix behind the scenes but allowing (a generally bad practice of) overrides).

I don't want to try to abstract/generalize the building of arbitrary software.  Sure, you mostly see devs try to provide the familiar `./configure --prefix=XXX && make && sudo make install`, but there's no one requiring them to provide that.  E.g. I've seen CMake-based projects that want you to use CMake directly instead of providing a configure script.  There's also scons-based projects, pure Makefiles without configure, etc.  So would need to still rely on Bro package author to provide the correct set of build commands for the dependency they need.

> I'm also game for a softer touch here.

I think this is what we'll have to do.  Did you have any preference/ideas ?

Here's a couple of my ideas with examples of how they would look:

# Option 1

Provide an optional `extra_instructions` field in bro-pkg.meta that can have arbitrary text to display to user upon installing:

```
$ bro-pkg install bro-test-package ssn-exposure domain-tld
The following packages will be INSTALLED:
  bro/jsiwek/bro-test-package (1.0.5)
     This package depends on librdkafka, please install it before proceeding.
  bro/sethhall/ssn-exposure (master)
  bro/sethhall/domain-tld (master)

Proceed? [Y/n] 
```

The entire "This package depends on librdkafka, please install it before proceeding" text would be what had been assigned to the field in bro-pkg.meta and can be anything.

# Option 2

Provide an optional `external_depends` field in bro-pkg.meta that's specifically meant for listing names of external dependencies.

```
The following packages will be INSTALLED:
  bro/jsiwek/bro-test-package (1.0.5)
  bro/sethhall/ssn-exposure (master)
  bro/sethhall/domain-tld (master)

Verify you have the following REQUIRED external dependencies before proceeding:
  bro/jsiwek/bro-test-package (1.0.5)
    librdkafka >= 0.9.4
    libdbus
 bro/sethhall/ssn-exposure (master)
    libssl/openssl

Proceed? [Y/n] 
```
  
With the "librdkafka >= 0.9.4",  "libdbus" and "libssl/openssl" bits having been taken from the values assigned to the `external_depends` fields of the associated package.

I lean toward Option 2.  It's more specific to the current problem we are trying to solve, the output format is going to look more structured to users, and it's possible to automate detection of versioning conflicts among external dependency requirements (though if a human is actually following the instructions, I'd think they'd probably be good at manually catching the conflict).

**Comment by JonZeolla** [comment]
I also agree that I would prefer option 2.  That said, how do we hook together the `build_command` with `external_depends`?  For instance, what if you install librdkafka in a non-standard directory?  It needs to be provided to the build_command like `--with-librdkafka=/usr/local`.

**Comment by jsiwek** [comment]
> I also agree that I would prefer option 2. That said, how do we hook together the build_command with external_depends? For instance, what if you install librdkafka in a non-standard directory? It needs to be provided to the build_command like --with-librdkafka=/usr/local.

Good point.  I think we get back to needing a generalized feedback mechanism to prompt user for extra info during the install process.

Example bro-pkg.meta:

```
[package]
build_command = ./configure --with-librdkafka=%(LIBRDKAFKA_ROOT)s && make
external_depends =
  librdkafka >= 0.9.4
  libdbus *
user_vars =
    LIBRDKAFKA_ROOT [/usr] "Path to librdkafa installation tree"
    LIBDBUS_ROOT [/usr] "Path to libdbus installation tree, just here for demonstration"
```

Example usage:

```
$ bro-pkg install bro-test-package
The following packages will be INSTALLED:
  bro/jsiwek/bro-test-package (1.0.5)

Verify you have the following REQUIRED external dependencies before proceeding:
  bro/jsiwek/bro-test-package (1.0.5)
    librdkafka >= 0.9.4
    libdbus *

bro/jsiwek/bro-test-package asks for "Path to librdkafa installation tree" ? [/usr] /usr/local
bro/jsiwek/bro-test-package asks for "Path to libdbus installation tree, just here for demonstration" ? [/usr] /opt/local

Proceed with installation? [Y/n] y
```

Could easily save the answers that users give somewhere in their ~/.bro-pkg dir and so that any future update/installs of the same package can provide the previous answer as the default.

**Comment by jsiwek** [comment]
I suppose the environment can also be queried in order to supply default answers and also to better support the --force options for skipping prompts of various bro-pkg operations.

**Comment by JonZeolla** [comment]
That's looking like a good first take at this.  Perhaps it should also be somehow obvious what the differences are for a bro cluster vs single node, such as requiring installation on all nodes (not just the manager/logger).

**Comment by jsiwek** [comment]
bro-pkg v1.1 now understands an `external_depends` metadata field:
http://bro-package-manager.readthedocs.io/en/stable/package.html#external-depends-field

as well as a `user_vars` field
http://bro-package-manager.readthedocs.io/en/stable/package.html#user-vars-field

Let me know if have any problems using those.
